const gap = { kind: 'sep', gap: '16' };
const divider = { kind: 'sep' };
const num = (value) => ({ shadow: { type: 'math_number', fields: { NUM: value } } });
const txt = (value) => ({ shadow: { type: 'text', fields: { TEXT: value } } });

export const toolbox = {
  kind: 'categoryToolbox',
  contents: [
    {
      kind: 'category', name: 'Objects', colour: '160',
      contents: [
        { kind: 'block', type: 'game_create_point', inputs: { X: num(100), Y: num(100) } },
        { kind: 'block', type: 'game_create_sprite', inputs: { X: num(100), Y: num(100), SCALE: num(5) } },
        { kind: 'block', type: 'game_create_rect', inputs: { X: num(100), Y: num(100), W: num(50), H: num(50) } },
        { kind: 'block', type: 'game_create_circle', inputs: { X: num(300), Y: num(300), R: num(15) } },
        { kind: 'block', type: 'game_create_text', inputs: { X: num(10), Y: num(10), SIZE: num(24) } },
        { kind: 'block', type: 'game_create_line', inputs: { X1: num(0), Y1: num(0), X2: num(100), Y2: num(100), WIDTH: num(2) } },
        { kind: 'block', type: 'game_create_button', inputs: { X: num(200), Y: num(300) } },
        gap,
        { kind: 'block', type: 'game_clone_do' },
        { kind: 'block', type: 'game_clone' },
        { kind: 'block', type: 'game_remove' },
        { kind: 'block', type: 'game_remove_all' },
      ],
    },
    {
      kind: 'category', name: 'Motion', colour: '230',
      contents: [
        { kind: 'block', type: 'game_move', inputs: { DX: num(5), DY: num(0) } },
        { kind: 'block', type: 'game_move_to', inputs: { X: num(300), Y: num(300) } },
        { kind: 'block', type: 'game_keep_inside' },
        { kind: 'block', type: 'game_turn_right', inputs: { DEG: num(15) } },
        { kind: 'block', type: 'game_turn_left', inputs: { DEG: num(15) } },
        { kind: 'block', type: 'game_follow', inputs: { SPEED: num(3) } },
        gap,
        { kind: 'block', type: 'game_x_position' },
        { kind: 'block', type: 'game_y_position' },
        { kind: 'block', type: 'game_rotation_of' },
      ],
    },
    {
      kind: 'category', name: 'Events', colour: '40',
      contents: [
        { kind: 'block', type: 'game_on_start' },
        { kind: 'block', type: 'game_every_frame' },
        gap,
        { kind: 'block', type: 'game_on_overlap' },
        { kind: 'block', type: 'game_on_click_obj' },
        { kind: 'block', type: 'game_on_hover_obj' },
        { kind: 'block', type: 'game_on_clone' },
        gap,
        { kind: 'block', type: 'game_wait', inputs: { MS: num(1000) } },
        { kind: 'block', type: 'game_after', inputs: { MS: num(1000) } },
        { kind: 'block', type: 'game_every', inputs: { MS: num(1000) } },
        { kind: 'block', type: 'game_cancel_timer' },
        gap,
        { kind: 'label', text: 'Game Control' },
        { kind: 'block', type: 'game_stop' },
        { kind: 'block', type: 'game_restart' },
      ],
    },
    {
      kind: 'category', name: 'Sensing', colour: '195',
      contents: [
        { kind: 'label', text: 'Keyboard' },
        { kind: 'block', type: 'game_on_key' },
        { kind: 'block', type: 'game_key_pressed' },
        gap,
        { kind: 'label', text: 'Mouse' },
        { kind: 'block', type: 'game_on_mouse' },
        { kind: 'block', type: 'game_mouse_x' },
        { kind: 'block', type: 'game_mouse_y' },
        { kind: 'block', type: 'game_mouse_down' },
        gap,
        { kind: 'label', text: 'Touching' },
        { kind: 'block', type: 'game_touches' },
        { kind: 'block', type: 'game_distance' },
        { kind: 'block', type: 'game_is_out' },
        { kind: 'block', type: 'game_touching_color' },
      ],
    },
    {
      kind: 'category', name: 'Looks', colour: '280',
      contents: [
        { kind: 'block', type: 'game_show' },
        { kind: 'block', type: 'game_hide' },
        { kind: 'block', type: 'game_say', inputs: { TEXT: txt('Hello!'), DUR: num(3000) } },
        gap,
        { kind: 'block', type: 'game_anim_set_frame', inputs: { FRAME: num(0) } },
        { kind: 'block', type: 'game_resize_sprite', inputs: { SCALE: num(5) } },
        gap,
        { kind: 'block', type: 'game_set_bg_image' },
        { kind: 'block', type: 'game_clear_bg_image' },
      ],
    },
    {
      kind: 'category', name: 'Stage', colour: '215',
      contents: [
        { kind: 'block', type: 'game_title' },
        { kind: 'block', type: 'game_background' },
        { kind: 'block', type: 'game_width' },
        { kind: 'block', type: 'game_height' },
      ],
    },
    {
      kind: 'category', name: 'Game Info', colour: '20',
      contents: [
        { kind: 'block', type: 'hud_create_score', inputs: { X: num(10), Y: num(10) } },
        { kind: 'block', type: 'hud_create_lives', inputs: { X: num(10), Y: num(40), MAX: num(3) } },
        { kind: 'block', type: 'hud_create_healthbar', inputs: { X: num(10), Y: num(70) } },
        { kind: 'block', type: 'hud_create_timer', inputs: { X: num(500), Y: num(10), SECS: num(60) } },
        gap,
        { kind: 'block', type: 'hud_score_add', inputs: { AMOUNT: num(1) } },
        { kind: 'block', type: 'hud_lives_change', inputs: { AMOUNT: num(1) } },
        { kind: 'block', type: 'hud_health_change', inputs: { AMOUNT: num(10) } },
        { kind: 'block', type: 'hud_timer_action' },
        { kind: 'block', type: 'hud_message', inputs: { TEXT: txt('Game Over!'), DUR: num(2) } },
        gap,
        { kind: 'label', text: 'More' },
        { kind: 'block', type: 'hud_get_value' },
        { kind: 'block', type: 'hud_set_value', inputs: { VALUE: num(0) } },
        { kind: 'block', type: 'hud_is_dead' },
        { kind: 'block', type: 'hud_timer_done' },
        gap,
        { kind: 'label', text: 'Events' },
        { kind: 'block', type: 'hud_on_score_reach', inputs: { VALUE: num(100) } },
        { kind: 'block', type: 'hud_on_zero' },
        { kind: 'block', type: 'hud_on_timer_done' },
        { kind: 'block', type: 'hud_on_value_change' },
      ],
    },
    {
      kind: 'category', name: 'Sound', colour: '310',
      contents: [
        { kind: 'block', type: 'game_play_custom_sound', inputs: { VOL: num(1) } },
        { kind: 'block', type: 'game_stop_sounds' },
        gap,
        { kind: 'block', type: 'game_sound', inputs: { FREQ: num(440), DUR: num(200) } },
        { kind: 'block', type: 'game_note', inputs: { DUR: num(300) } },
      ],
    },
    divider,
    {
      kind: 'category', name: 'Logic', colour: '210',
      contents: [
        { kind: 'block', type: 'gm_if_chain' },
        { kind: 'block', type: 'gm_if_else_chain' },
        { kind: 'block', type: 'logic_compare' },
        { kind: 'block', type: 'logic_operation' },
        { kind: 'block', type: 'logic_negate' },
        { kind: 'block', type: 'logic_boolean' },
      ],
    },
    {
      kind: 'category', name: 'Loops', colour: '120',
      contents: [
        { kind: 'block', type: 'controls_repeat_ext', inputs: { TIMES: num(10) } },
        { kind: 'block', type: 'controls_whileUntil' },
        { kind: 'block', type: 'controls_for', inputs: { FROM: num(1), TO: num(10), BY: num(1) } },
        { kind: 'block', type: 'controls_flow_statements' },
      ],
    },
    {
      kind: 'category', name: 'Math', colour: '230',
      contents: [
        { kind: 'block', type: 'math_number', fields: { NUM: 0 } },
        { kind: 'block', type: 'math_arithmetic' },
        { kind: 'block', type: 'game_random_int', inputs: { MIN: num(1), MAX: num(100) } },
        { kind: 'block', type: 'game_random_float', inputs: { MIN: num(0), MAX: num(1) } },
        { kind: 'block', type: 'game_random_color' },
        { kind: 'block', type: 'game_choice' },
        gap,
        { kind: 'block', type: 'math_modulo' },
        { kind: 'block', type: 'game_sqrt', inputs: { NUM: num(9) } },
        { kind: 'block', type: 'game_log', inputs: { NUM: num(100) } },
        gap,
        { kind: 'block', type: 'mp_round', inputs: { NUM: num(3.7) } },
        { kind: 'block', type: 'mp_floor', inputs: { NUM: num(3.7) } },
        { kind: 'block', type: 'mp_ceil', inputs: { NUM: num(3.2) } },
        { kind: 'block', type: 'mp_abs', inputs: { NUM: num(-5) } },
        gap,
        { kind: 'block', type: 'mp_min', inputs: { A: num(5), B: num(10) } },
        { kind: 'block', type: 'mp_max', inputs: { A: num(5), B: num(10) } },
        { kind: 'block', type: 'game_lerp', inputs: { A: num(0), B: num(100), T: num(0.5) } },
        { kind: 'block', type: 'game_clamp', inputs: { VAL: num(50), MIN: num(0), MAX: num(100) } },
        gap,
        { kind: 'block', type: 'mp_sin', inputs: { NUM: num(0) } },
        { kind: 'block', type: 'mp_cos', inputs: { NUM: num(0) } },
        { kind: 'block', type: 'mp_pi' },
        { kind: 'block', type: 'mp_e' },
        { kind: 'block', type: 'mp_degrees', inputs: { NUM: num(3.14) } },
        { kind: 'block', type: 'mp_radians', inputs: { NUM: num(180) } },
      ],
    },
    {
      kind: 'category', name: 'Text', colour: '160',
      contents: [
        { kind: 'block', type: 'text', fields: { TEXT: 'hello' } },
        { kind: 'block', type: 'game_join', inputs: { A: txt('Score: '), B: txt('') } },
        { kind: 'block', type: 'game_str' },
        { kind: 'block', type: 'game_to_number' },
        gap,
        { kind: 'block', type: 'mp_string_length', inputs: { TEXT: txt('hello') } },
        { kind: 'block', type: 'game_is_empty' },
        { kind: 'block', type: 'mp_string_char_at', inputs: { INDEX: num(0), TEXT: txt('hello') } },
        { kind: 'block', type: 'game_substring', inputs: { TEXT: txt('hello world'), FROM: num(0), TO: num(5) } },
        { kind: 'block', type: 'mp_string_find', inputs: { TEXT: txt('o'), SEARCH: txt('hello') } },
        gap,
        { kind: 'block', type: 'mp_string_upper', inputs: { TEXT: txt('hello') } },
        { kind: 'block', type: 'mp_string_lower', inputs: { TEXT: txt('HELLO') } },
        { kind: 'block', type: 'mp_string_strip', inputs: { TEXT: txt('  text  ') } },
        gap,
        { kind: 'block', type: 'mp_string_contains', inputs: { TEXT: txt('hello world'), SEARCH: txt('world') } },
        { kind: 'block', type: 'game_chr', inputs: { CODE: num(65) } },
        { kind: 'block', type: 'game_ord' },
      ],
    },
    {
      kind: 'category', name: 'Variables', colour: '330',
      custom: 'VARIABLE',
    },
    divider,
    {
      kind: 'category', name: 'Advanced', colour: '260',
      contents: [
        {
          kind: 'category', name: 'Physics & Groups', colour: '160',
          contents: [
            { kind: 'label', text: 'Create' },
            { kind: 'label', text: 'Physics' },
            { kind: 'block', type: 'game_set_velocity', inputs: { VX: num(3), VY: num(0) } },
            { kind: 'block', type: 'game_set_acceleration', inputs: { AX: num(0), AY: num(0.5) } },
            { kind: 'block', type: 'game_set_bounce', inputs: { VAL: num(0.8) } },
            { kind: 'block', type: 'game_set_friction', inputs: { VAL: num(0.98) } },
            { kind: 'block', type: 'game_physics_toggle' },
            gap,
            { kind: 'label', text: 'Collision & Groups' },
            { kind: 'block', type: 'game_push_out' },
            { kind: 'block', type: 'game_bounce_off' },
            { kind: 'block', type: 'game_create_group' },
            { kind: 'block', type: 'game_group_add' },
            { kind: 'block', type: 'game_group_remove' },
            { kind: 'block', type: 'game_group_count' },
            { kind: 'block', type: 'game_group_any_touch' },
            { kind: 'block', type: 'game_group_remove_all' },
          ],
        },
        {
          kind: 'category', name: 'Tweening', colour: '230',
          contents: [
            { kind: 'block', type: 'game_tween', inputs: { TARGET: num(300), DUR: num(500) } },
            { kind: 'block', type: 'game_cancel_tweens' },
          ],
        },
        {
          kind: 'category', name: 'Special Events', colour: '40',
          contents: [
            { kind: 'block', type: 'game_on_array_item_where' },
            { kind: 'block', type: 'game_print', inputs: { TEXT: txt('hello') } },
          ],
        },
        {
          kind: 'category', name: 'Effects & Particles', colour: '280',
          contents: [
            { kind: 'block', type: 'game_set_prop', inputs: { VALUE: num(0) } },
            { kind: 'block', type: 'game_get_prop' },
            { kind: 'block', type: 'game_set_fixed' },
            { kind: 'block', type: 'game_set_layer', inputs: { LAYER: num(0) } },
            gap,
            { kind: 'label', text: 'Particles' },
            { kind: 'block', type: 'game_preset', inputs: { X: num(300), Y: num(300) } },
            { kind: 'block', type: 'game_create_emitter', inputs: { X: num(300), Y: num(500) } },
            { kind: 'block', type: 'game_emitter_toggle' },
            { kind: 'block', type: 'game_move_emitter', inputs: { X: num(0), Y: num(0) } },
            { kind: 'block', type: 'game_remove_emitter' },
          ],
        },
        {
          kind: 'category', name: 'Mobile & Sensors', colour: '195',
          contents: [
            { kind: 'label', text: 'Extra sensing' },
            { kind: 'block', type: 'game_hit_test', inputs: { X: num(0), Y: num(0) } },
            { kind: 'block', type: 'game_frame_count' },
            gap,
            { kind: 'label', text: 'Color' },
            { kind: 'block', type: 'game_color_at', inputs: { X: num(300), Y: num(300) } },
            gap,
            { kind: 'label', text: 'Mobile' },
            { kind: 'block', type: 'game_show_controls' },
            { kind: 'block', type: 'game_hide_controls' },
            { kind: 'block', type: 'game_on_dpad' },
            { kind: 'block', type: 'game_dpad_pressed' },
            { kind: 'block', type: 'game_on_button' },
            { kind: 'block', type: 'game_button_pressed' },
            { kind: 'block', type: 'game_request_tilt' },
            { kind: 'block', type: 'game_tilt' },
          ],
        },
        {
          kind: 'category', name: 'Scenes, Camera & Tilemaps', colour: '215',
          contents: [
            { kind: 'block', type: 'game_show_grid' },
            { kind: 'block', type: 'game_hide_grid' },
            gap,
            { kind: 'label', text: 'Effects' },
            { kind: 'block', type: 'game_shake', inputs: { INTENSITY: num(5), DUR: num(300) } },
            { kind: 'block', type: 'game_flash', inputs: { DUR: num(200) } },
            { kind: 'block', type: 'game_transition', inputs: { DUR: num(500) } },
            gap,
            { kind: 'label', text: 'Scenes' },
            { kind: 'block', type: 'game_define_scene', inputs: { NAME: txt('menu') } },
            { kind: 'block', type: 'game_switch_scene', inputs: { NAME: txt('menu') } },
            { kind: 'block', type: 'game_switch_scene_transition', inputs: { NAME: txt('level1'), DUR: num(500) } },
            { kind: 'block', type: 'game_get_scene' },
            gap,
            { kind: 'label', text: 'Camera' },
            { kind: 'block', type: 'game_camera_follow', inputs: { SMOOTH: num(0.1) } },
            { kind: 'block', type: 'game_camera_set', inputs: { VAL: num(0) } },
            { kind: 'block', type: 'game_camera_get' },
            gap,
            { kind: 'label', text: 'TileMap' },
            { kind: 'block', type: 'game_create_tilemap', inputs: { COLS: num(20), ROWS: num(15), SIZE: num(32) } },
            { kind: 'block', type: 'game_set_tile_palette', inputs: { TYPE: num(1) } },
            { kind: 'block', type: 'game_set_tile', inputs: { COL: num(0), ROW: num(0), TYPE: num(1) } },
            { kind: 'block', type: 'game_get_tile', inputs: { COL: num(0), ROW: num(0) } },
            { kind: 'block', type: 'game_set_tile_data' },
            { kind: 'block', type: 'game_tile_at_pixel', inputs: { X: num(0), Y: num(0) } },
            { kind: 'block', type: 'game_overlaps_solid' },
            { kind: 'block', type: 'game_tilemap_push_out' },
          ],
        },
        {
          kind: 'category', name: 'Animation', colour: '45',
          contents: [
            { kind: 'block', type: 'game_anim_play', inputs: { FPS: num(8) } },
            { kind: 'block', type: 'game_anim_stop' },
            { kind: 'block', type: 'game_anim_frame' },
            { kind: 'block', type: 'game_anim_frame_count' },
            { kind: 'block', type: 'game_anim_is_animating' },
          ],
        },
        {
          kind: 'category', name: 'Arrays', colour: '200',
          contents: [
            { kind: 'label', text: 'Create' },
            { kind: 'block', type: 'mp_array_create' },
            { kind: 'block', type: 'mp_array_empty' },
            gap,
            { kind: 'label', text: 'Read' },
            { kind: 'block', type: 'mp_array_length' },
            { kind: 'block', type: 'mp_array_get_index', inputs: { INDEX: num(0) } },
            { kind: 'block', type: 'mp_array_first' },
            { kind: 'block', type: 'mp_array_last' },
            { kind: 'block', type: 'mp_array_pop_last' },
            { kind: 'block', type: 'mp_array_pop_first' },
            { kind: 'block', type: 'mp_array_pop_at', inputs: { INDEX: num(0) } },
            gap,
            { kind: 'label', text: 'Modify' },
            { kind: 'block', type: 'mp_array_set_index', inputs: { INDEX: num(0) } },
            { kind: 'block', type: 'mp_array_push' },
            { kind: 'block', type: 'mp_array_unshift' },
            { kind: 'block', type: 'mp_array_insert_at', inputs: { INDEX: num(0) } },
            gap,
            { kind: 'block', type: 'mp_array_remove_last' },
            { kind: 'block', type: 'mp_array_remove_first' },
            { kind: 'block', type: 'mp_array_remove_index', inputs: { INDEX: num(0) } },
            gap,
            { kind: 'label', text: 'Operations' },
            { kind: 'block', type: 'mp_array_for_each' },
            { kind: 'block', type: 'mp_array_find' },
            { kind: 'block', type: 'mp_array_reverse' },
          ],
        },
        {
          kind: 'category', name: 'Functions', colour: '290',
          custom: 'GM_PROCEDURES',
        },
      ],
    },
  ],
};
