/**
 * Built-in pixel art background definitions for the Py Game Maker.
 * Each background is a 30×20 grid (600×400 aspect when scaled 20x).
 * Rows are strings, each character maps to a color in the palette.
 */

const BG_CATEGORIES = [
  { id: 'nature', name: 'Nature' },
  { id: 'space', name: 'Space' },
  { id: 'indoor', name: 'Indoor' },
  { id: 'game', name: 'Game Scenes' },
  { id: 'abstract', name: 'Abstract' },
];

const DEFS = {
  // ── Nature ──
  blue_sky: {
    cat: 'nature',
    w: 30, h: 20,
    palette: { b: '#87CEEB', B: '#5DA8D6', w: '#FFFFFF', c: '#E8E8E8', g: '#4CAF50', G: '#388E3C', d: '#6D4C41', '.': '#87CEEB' },
    rows: [
      'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
      'BBBBBBBBBBBBBBBBBBbBBBBBBBBBBB',
      'bbbBBBBbbbbbbBBbbbbbbbBBBbbbbb',
      'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
      'bbbbbwwwbbbbbbbbbbwwwbbbbbbbbbb',
      'bbbbwwwwwbbbbbbbbwwwwwbbbbbbbbb',
      'bbbwwwwwwwbbbbbbwwwwwwwbbbbbbbb',
      'bbbbwwwwwbbccbbbbwwwwwbbbbbbbbb',
      'bbbbbwwwbbcccccbbbwwwbbbbbbbbbb',
      'bbbbbbbbbcccccccbbbbbbbbbbbbbb',
      'bbbbbbbbbbcccccbbbbbbbbbbbbbbb',
      'bbbbbbbbbbbcccbbbbbbbbbbbbbbbb',
      'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
      'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
      'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
      'gGgGgGgGgGgGgGgGgGgGgGgGgGgGgG',
      'GgGgGgGgGgGgGgGgGgGgGgGgGgGgGg',
      'gGgGgGgGgGgGgGgGgGgGgGgGgGgGgG',
      'GgGgGgGgGgGgGgGgGgGgGgGgGgGgGg',
      'gggggggggggggggggggggggggggggg',
    ],
  },
  sunset: {
    cat: 'nature',
    w: 30, h: 20,
    palette: { R: '#FF4500', O: '#FF8C00', Y: '#FFD700', P: '#FF6EB4', p: '#FF69B4', D: '#8B0000', r: '#CD5C5C', y: '#FFA07A', g: '#2E2E1F', G: '#3A3A28', s: '#FFD700' },
    rows: [
      'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
      'DDDDrrrrDDDDDDDDDDDDDDrrrrDDDDDD',
      'DDrrrRRRrrDDDDDDDDDDrrRRRrrDDDDD',
      'RRRRRRRRRRRRDDDDDDRRRRRRRRRRrrR',
      'RRRROOORRRRRRRRRRRRRROOORRRRrrR',
      'OOOOOOOOOORRRRRRROOOOOOOOOORrrR',
      'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOrR',
      'OOOOYYYOOOOOOOOOOOOYYYOOOOOOOrO',
      'YYYYYYYYYYOOOsOOYYYYYYYYYYOOOOO',
      'YYYYYYYYYYYYYsYYYYYYYYYYYYYOOOY',
      'yyyyYYYYYYYYYsYYYYYYYYYYYyyyYYY',
      'yyyyyyyyyYYYYsYYYYYYyyyyyyyyYYYy',
      'yyyyyyyyyyyyysyyyyyyyyyyyyyyyyyyy',
      'gggggggggggggsgggggggggggggggggg',
      'GgGgGgGgGgGgGsGgGgGgGgGgGgGgGg',
      'gGgGgGgGgGgGgGgGgGgGgGgGgGgGgG',
      'GgGgGgGgGgGgGgGgGgGgGgGgGgGgGg',
      'gGgGgGgGgGgGgGgGgGgGgGgGgGgGgG',
      'gggggggggggggggggggggggggggggggg',
      'gggggggggggggggggggggggggggggggg',
    ],
  },
  ocean: {
    cat: 'nature',
    w: 30, h: 20,
    palette: { b: '#0077BE', B: '#005A8E', d: '#003F5E', D: '#002A3E', w: '#FFFFFF', c: '#87CEEB', f: '#00BCD4', s: '#E0C068', S: '#C8A850', '.': '#0066AA' },
    rows: [
      'cccccccccccccccccccccccccccccc',
      'cccccccccccccccccccccwwccccccc',
      'cccwwwcccccccccwwwccwwwwcccccc',
      'ccwwwwwcccccccwwwwwccwwwccccccc',
      'cccwwwccccccccwwwwccccccccccccc',
      'cccccccccccccccccccccccccccccc',
      'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
      'bBbbBbbbbBbbbbbbbBbbbbBbbbbBbb',
      'BBbBBbBbBBBbbbbBBBbBbBBBbbBBBb',
      'BBBBBBBBBBBBbbBBBBBBBBBBBBBBBB',
      'BdBBBdBBBdBBBBBdBBBdBBBdBBBdBB',
      'ddBdddBdddBBBdddBdddBdddBdddBd',
      'ddddddddddddddddddddddddddddd',
      'dDdddDdddDdddDdddDdddDdddDdddd',
      'DDDdDDDdDDDdDDDdDDDdDDDdDDDdDDD',
      'ssSSSsssSSSsssSSSsssSSSsssSSSss',
      'SsSSSSsSSSSSsSSSSSsSSSSSsSSSSSs',
      'ssssssssssssssssssssssssssssss',
      'sSsSsSsSsSsSsSsSsSsSsSsSsSsSsS',
      'ssssssssssssssssssssssssssssss',
    ],
  },
  forest: {
    cat: 'nature',
    w: 30, h: 20,
    palette: { g: '#228B22', G: '#1B6B1B', d: '#0D4D0D', t: '#8B4513', T: '#654321', l: '#90EE90', L: '#66CC66', k: '#4A2E0D', s: '#1A1A0D', S: '#87CEEB' },
    rows: [
      'SSSSSSSSgSSSSSSSSgSSSSSSSSgSSSS',
      'SSSSSSSggSSSSSSSggSSSSSSSggSSSS',
      'SSSSSSgggSSSSSSgggSSSSSSgggSSSS',
      'SSSSSgGggSSSSSgGggSSSSSgGggSSSS',
      'SSSSggGgggSSSggGgggSSSggGgggSSS',
      'SSSgggGggggSgggGggggSgggGggggSS',
      'SSggggGgggggggggGgggggggggGgggg',
      'SgGgggGggggGgGgggGggggGgGgggGgg',
      'ggGGggGGgggGgGGggGGgggGgGGggGGg',
      'gGGGgGGGgggGgGGGgGGGgggGgGGGgGG',
      'dGGGdGGGdGGGdGGGdGGGdGGGdGGGdGG',
      'ddGdddGdddGdddGdddGdddGdddGdddd',
      'SSSStSSSSSSSSStSSSSSSSSStSSSSSS',
      'SSSStSSSSSSSSStSSSSSSSSStSSSSSS',
      'SSSStSSSSSSSSStSSSSSSSSStSSSSSS',
      'llllllllllllllllllllllllllllll',
      'lLlLlLlLlLlLlLlLlLlLlLlLlLlLlL',
      'LlLlLlLlLlLlLlLlLlLlLlLlLlLlLl',
      'llllllllllllllllllllllllllllll',
      'ssssssssssssssssssssssssssssss',
    ],
  },
  mountains: {
    cat: 'nature',
    w: 30, h: 20,
    palette: { b: '#87CEEB', B: '#6BAED6', w: '#FFFFFF', m: '#696969', M: '#808080', d: '#555555', g: '#4CAF50', G: '#388E3C', s: '#A0A0A0', '.': '#87CEEB' },
    rows: [
      'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
      'bbbbbbbbbbbbbbbbbbbbbbbbbwbbbbb',
      'bbbbbbbbbbbbbbbbbbbbbbbbwwbbbbb',
      'bbbbbbbwbbbbbbbbbbbbbbwwwwbbbbb',
      'bbbbbbwwwbbbbbbbbbbbwwwMwwbbbbb',
      'bbbbbwwMwwbbbbbbbbwwMMMMwwbbbbb',
      'bbbbwwMMMwwbbbbbwwMMMMMMMwbbbbb',
      'bbbwMMMMMMwwbbwwMMMMMMMMMwwbbbb',
      'bbwMMMMMMMwwwwMMMMMMMMMMMMwbbbb',
      'bwMMMMMMMMMwwMMMdMMMMMMMMMMwbbb',
      'wMMMdMMMMMMMMMMMddMMMMdMMMMwbbb',
      'MMdddMMMdMMMMMdddddMMddMMMMwbb',
      'MddddddddMMdddddddddddddMMMwb',
      'ddddddddddddddddddddddddddMwb',
      'ddddddddddddddddddddddddddddd',
      'gGgGgGgGgGgGgGgGgGgGgGgGgGgGgG',
      'GgGgGgGgGgGgGgGgGgGgGgGgGgGgGg',
      'gGgGgGgGgGgGgGgGgGgGgGgGgGgGgG',
      'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGg',
      'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
    ],
  },

  // ── Space ──
  starfield: {
    cat: 'space',
    w: 30, h: 20,
    palette: { '.': '#0A0A1A', s: '#FFFFFF', d: '#888888', b: '#4444FF', p: '#FF44FF', y: '#FFFF44', c: '#44FFFF' },
    rows: [
      '..s.........d............s....',
      '............................s.',
      '.......s..........s...........',
      '...d.........s................',
      '.........s..............d.....',
      '..s.............s.............',
      '................s.......s.....',
      '.........d..........s.........',
      '....s.................s.......',
      '..............s.......d.......',
      '.......s..........s...........',
      '....d.....s...................',
      '..............d........s......',
      '.s..........s.................',
      '.......d..............s.......',
      '...s..........s.......d.......',
      '..............d..............s',
      '......s..........s............',
      '.d..........s.............d...',
      '..........d.............s.....',
    ],
  },
  nebula: {
    cat: 'space',
    w: 30, h: 20,
    palette: { '.': '#0A0A1A', d: '#0D0D2B', p: '#2D1B4E', P: '#4A2C7A', m: '#6A3D9A', M: '#8844BB', b: '#3344AA', s: '#FFFFFF', c: '#4466DD' },
    rows: [
      '...s.d..........d.....s.......',
      '.....dd...s.....dd......d.....',
      '...s.dpp........dpp....s......',
      '....dpPPpd....s.dpPpd.........',
      '...dpPPPPpd.....dPPPpd.....s.',
      '..dpPmMmPPpd...dpMmPPpd......',
      '.dpPmMMmPPppd.dpMMMPPppd.....',
      'dpPPmMMmPPpppddpMMMPPpppd....',
      'dpPPmMmPPppppddpMMPPpppdd.s..',
      'dpPPPPPPppppddddPPPpppddd....',
      '.dppPPPpppdddddddPPppddd.....',
      '..dpppppddddd..s.dpppddd.....',
      '...ddddddd.......ddddd...s...',
      '....ddddd...s.....ddd........',
      '.s...ddd..........dd....s....',
      '......d.....s......d..........',
      '.........d..........d.........',
      '..s.....dd....s.....dd...s....',
      '........d.............d.......',
      '.....s.........s..............',
    ],
  },
  planet: {
    cat: 'space',
    w: 30, h: 20,
    palette: { '.': '#0A0A1A', s: '#FFFFFF', b: '#2244AA', B: '#1133BB', c: '#3366CC', g: '#22AA44', G: '#118833', w: '#DDDDDD', y: '#AA8833', r: '#883322' },
    rows: [
      '..s.........s............s....',
      '..............................',
      '.......s..........s...........',
      '...........bbbbbbb............',
      '........bbbBBccccbbb..........',
      '......bbbBBccgGgccccbb........',
      '.....bbBBcccgGGGgcccccb.s.....',
      '....bBBBccggGGGGGgcccccb......',
      '...bBBBcccgGGGgGGgccccccb.....',
      '..s.bBccccgGggggGgcccccb......',
      '....bBcccccggggGGgccccccb.....',
      '....bBBccccccgGGgcccccccb.....',
      '.....bBBcccccggggccccccb.s....',
      '......bbbBccccccccccccb........',
      '........bbbBBccccbbbb..........',
      '...........bbbbbbb.............',
      '............s................s.',
      '.s...........s................',
      '......s..........s............',
      '..........s.............s.....',
    ],
  },

  // ── Indoor ──
  dungeon: {
    cat: 'indoor',
    w: 30, h: 20,
    palette: { d: '#333333', D: '#444444', b: '#555555', B: '#666666', t: '#222222', f: '#8B4513', F: '#6B3310', '.': '#1A1A1A' },
    rows: [
      'bBbBbBbBbBbBbBbBbBbBbBbBbBbBbB',
      'BbBbBbBbBbBbBbBbBbBbBbBbBbBbBb',
      'bBbBbBbBbBbBbBbBbBbBbBbBbBbBbB',
      'ddddddddddddddddddddddddddddd',
      'd.....d.....d.....d.....d....d',
      'd.....d.....d.....d.....d....d',
      'd.....d.....d.....d.....d....d',
      'ddddddddddddddddddddddddddddd',
      'd.....d.....d.....d.....d....d',
      'd.....d.....d.....d.....d....d',
      'd.....d.....d.....d.....d....d',
      'ddddddddddddddddddddddddddddd',
      'd.....d.....d.....d.....d....d',
      'd.....d.....d.....d.....d....d',
      'd.....d.....d.....d.....d....d',
      'ddddddddddddddddddddddddddddd',
      'fFfFfFfFfFfFfFfFfFfFfFfFfFfFfF',
      'FfFfFfFfFfFfFfFfFfFfFfFfFfFfFf',
      'fFfFfFfFfFfFfFfFfFfFfFfFfFfFfF',
      'FfFfFfFfFfFfFfFfFfFfFfFfFfFfFf',
    ],
  },
  brick_wall: {
    cat: 'indoor',
    w: 30, h: 20,
    palette: { r: '#AA4444', R: '#CC5555', d: '#883333', m: '#666666', '.': '#555555' },
    rows: [
      'rRrRrR.rRrRrR.rRrRrR.rRrRrR.r',
      'rRrRrR.rRrRrR.rRrRrR.rRrRrR.r',
      '..............................',
      'RrR.rRrRrR.rRrRrR.rRrRrR.rRrR',
      'RrR.rRrRrR.rRrRrR.rRrRrR.rRrR',
      '..............................',
      'rRrRrR.rRrRrR.rRrRrR.rRrRrR.r',
      'rRrRrR.rRrRrR.rRrRrR.rRrRrR.r',
      '..............................',
      'RrR.rRrRrR.rRrRrR.rRrRrR.rRrR',
      'RrR.rRrRrR.rRrRrR.rRrRrR.rRrR',
      '..............................',
      'rRrRrR.rRrRrR.rRrRrR.rRrRrR.r',
      'rRrRrR.rRrRrR.rRrRrR.rRrRrR.r',
      '..............................',
      'RrR.rRrRrR.rRrRrR.rRrRrR.rRrR',
      'RrR.rRrRrR.rRrRrR.rRrRrR.rRrR',
      '..............................',
      'rRrRrR.rRrRrR.rRrRrR.rRrRrR.r',
      'rRrRrR.rRrRrR.rRrRrR.rRrRrR.r',
    ],
  },

  // ── Game Scenes ──
  city_night: {
    cat: 'game',
    w: 30, h: 20,
    palette: { '.': '#0A0A2E', s: '#FFFFFF', b: '#222244', B: '#1A1A3A', y: '#FFFF00', w: '#333355', W: '#2A2A4A', g: '#444444', r: '#444466', R: '#333355' },
    rows: [
      '..s.........s.......s.........',
      '.............s.......s...s....',
      '....s..........................',
      '..........s...................',
      '...s..............s...........',
      '.........bbb..bbbbb...........',
      '.....bbb.byb..bybbb..bb......',
      '..bb.byb.byb..bybyb..byb.....',
      '..by.byb.byb..bybyb..byb.bb.',
      '..by.byb.bbb.bbybbb..byb.byb',
      'bbby.byb.bbb.bbybybbbbybbbbyb',
      'bbyb.bbb.bbb.bbbbybbbbybbbbyb',
      'bbyb.bbb.bbb.bbbbbbbbbbbbbbyb',
      'ggggggggggggggggggggggggggggggg',
      'ggggggggggggggggggggggggggggggg',
      'rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr',
      'rRrRrRrRrRrRrRrRrRrRrRrRrRrRrR',
      'RRRRRRRRRRRRRRRRRRRRRRRRRRRRRR',
      'rRrRrRrRrRrRrRrRrRrRrRrRrRrRrR',
      'RRRRRRRRRRRRRRRRRRRRRRRRRRRRRR',
    ],
  },
  underwater: {
    cat: 'game',
    w: 30, h: 20,
    palette: { b: '#006994', B: '#005577', d: '#004466', D: '#003355', g: '#22AA66', G: '#118844', s: '#AADDEE', w: '#66CCFF', y: '#DDAA44', Y: '#CC9933' },
    rows: [
      'bbbbwbbbbbbbbwbbbbbbbbbwbbbbbb',
      'bbbwwbbbbbbbwwbbbbbbbbwwbbbbbb',
      'bbbbbbbbbbbbbbbbbbbwbbbbbbbwbb',
      'bBbbbBbbbBbbbwbbbBbbbbBbbbBbbb',
      'BBbBBBbBBBbbbbbBBBbBBBBbBBBbBB',
      'BBBBBBBBBBBbbBBBBBBBBBBBBBBBBB',
      'dBBBdBBBdBBBBBdBBBdBBBdBBBdBBB',
      'ddBdddBdddBBdddBdddBdddBdddBdd',
      'ddddddddddddddddddddddddddddd',
      'DdddDdddDdddDdddDdddDdddDdddDd',
      'DDDdDDDdDDDdDDDdDDDdDDDdDDDdDDD',
      'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDd',
      'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDd',
      'DDDgDDDDDDDDDDDDDDDDgGDDDDDDDDD',
      'DDgGgDDDDDDgDDDDDDgGGGgDDDDDDDD',
      'DgGGGgDDDDgGgDDDgGGGGGgDDDgDDD',
      'gGGGGGgDDgGGGgDgGGGGGGGgDgGgDg',
      'yYyYyyYyYyYyYyyYyYyYyYyyYyYyYy',
      'YyYyYyYyYyYyYyYyYyYyYyYyYyYyYy',
      'yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy',
    ],
  },
  desert: {
    cat: 'game',
    w: 30, h: 20,
    palette: { b: '#87CEEB', B: '#6BAED6', s: '#FFD700', y: '#F4A460', Y: '#DEB887', d: '#C4A35A', D: '#B89545', g: '#8B7355', '.': '#87CEEB', w: '#FFFFFF' },
    rows: [
      'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
      'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
      'bbbbbbbbbbbbbbbbbbbbbbbbbwwbbb',
      'bbbbbbbbbbbbbbbbbbbbbbbbwwwwbb',
      'bbbbbwwbbbbbbbbbbbbbbbbbwwwbbb',
      'bbbbwwwwbbbbbbbbbbbbbbbbbbbbbb',
      'bbbbbwwbbbbbbbbbbbbbbbbbbbbbbb',
      'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
      'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
      'yyyyyyyYyyyYYyyyyyyYyyyYYyyyyy',
      'yyyyYYYYYYYYYYYYYYYYYYYYYYyyyy',
      'yYYYYYYYYYYYYYYYYYYYYYYYYYYYYy',
      'YYYYdYYYYYYYYYYYYYYYdYYYYYYYYY',
      'YYYddDYYYdYYYYYYYYYddDYYYdYYYY',
      'dddddDDddDDdddddddddDDddDDdddd',
      'dDDDDDDDDDDDDDDDDDDDDDDDDDDDdd',
      'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDd',
      'ssssssssssssssssssssssssssssss',
      'sSsSsSsSsSsSsSsSsSsSsSsSsSsSsS',
      'ssssssssssssssssssssssssssssss',
    ],
  },
  lava: {
    cat: 'game',
    w: 30, h: 20,
    palette: { '.': '#1A0A0A', d: '#330A0A', r: '#AA2200', R: '#CC3300', o: '#FF6600', O: '#FF8800', y: '#FFCC00', Y: '#FFDD33', g: '#444444', G: '#333333' },
    rows: [
      'ggGgGgGgGgGgGgGgGgGgGgGgGgGgG',
      'GgGgGgGgGgGgGgGgGgGgGgGgGgGgG',
      'gGgGgGgGgGgGgGgGgGgGgGgGgGgGg',
      'gggGGGgggGGGgggGGGgggGGGgggGGG',
      '...d...d...d...d...d...d...d..',
      '..ddd..ddd..ddd..ddd..ddd..ddd',
      '.drrdd.drrdd.drrdd.drrdd.drrdd',
      'drRRrddRRRrddRRrddRRRrddRRRrd',
      'rRoORrrRoORrrRoORrrRoORrrRoORr',
      'RoOOoRRoOOoRRoOOoRRoOOoRRoOOoR',
      'oOYOoRoOYOoRoOYOoRoOYOoRoOYOoR',
      'OYYYOoOYYYOoOYYYOoOYYYOoOYYYOo',
      'oOYOoRoOYOoRoOYOoRoOYOoRoOYOoR',
      'RoOOoRRoOOoRRoOOoRRoOOoRRoOOoR',
      'rRoORrrRoORrrRoORrrRoORrrRoORr',
      'drRRrddRRRrddRRrddRRRrddRRRrd',
      '.drrdd.drrdd.drrdd.drrdd.drrdd',
      '..ddd..ddd..ddd..ddd..ddd..ddd',
      '...d...d...d...d...d...d...d..',
      '..............................',
    ],
  },
  ice: {
    cat: 'game',
    w: 30, h: 20,
    palette: { w: '#FFFFFF', l: '#E0F0FF', b: '#B0D4F1', B: '#88BBE0', d: '#6699CC', D: '#4477AA', c: '#AADDFF', s: '#F0F8FF' },
    rows: [
      'llllslllllllslllllllslllllllsll',
      'lslllllslllllllslllllllslllllls',
      'llllllllllllllllllllllllllllll',
      'bbbblbbbbbblbbbbbblbbbbbblbbbb',
      'bblbbbbblbbbbblbbbbblbbbbblbbb',
      'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
      'BBbbBBbbBBbbBBbbBBbbBBbbBBbbBB',
      'bBBbbBBbbBBbbBBbbBBbbBBbbBBbbB',
      'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBb',
      'dBBBdBBBdBBBdBBBdBBBdBBBdBBBdB',
      'ddBdddBdddBdddBdddBdddBdddBddd',
      'ddddddddddddddddddddddddddddd',
      'dDdddDdddDdddDdddDdddDdddDdddd',
      'DDDdDDDdDDDdDDDdDDDdDDDdDDDdDDD',
      'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
      'wwwswwwwwwswwwwwwswwwwwwswwwwww',
      'wswwwwwswwwwwwswwwwwwswwwwwwsww',
      'wwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
      'cccccccccccccccccccccccccccccc',
      'csccsccsccsccsccsccsccsccsccscc',
    ],
  },

  // ── Abstract ──
  grid: {
    cat: 'abstract',
    w: 30, h: 20,
    palette: { '.': '#1A1A2E', g: '#2A2A4E', G: '#333366' },
    rows: [
      'GgGgGgGgGgGgGgGgGgGgGgGgGgGgGg',
      'g.....g.....g.....g.....g.....g',
      'G.....G.....G.....G.....G.....G',
      'g.....g.....g.....g.....g.....g',
      'G.....G.....G.....G.....G.....G',
      'GgGgGgGgGgGgGgGgGgGgGgGgGgGgGg',
      'g.....g.....g.....g.....g.....g',
      'G.....G.....G.....G.....G.....G',
      'g.....g.....g.....g.....g.....g',
      'G.....G.....G.....G.....G.....G',
      'GgGgGgGgGgGgGgGgGgGgGgGgGgGgGg',
      'g.....g.....g.....g.....g.....g',
      'G.....G.....G.....G.....G.....G',
      'g.....g.....g.....g.....g.....g',
      'G.....G.....G.....G.....G.....G',
      'GgGgGgGgGgGgGgGgGgGgGgGgGgGgGg',
      'g.....g.....g.....g.....g.....g',
      'G.....G.....G.....G.....G.....G',
      'g.....g.....g.....g.....g.....g',
      'GgGgGgGgGgGgGgGgGgGgGgGgGgGgGg',
    ],
  },
  gradient_blue: {
    cat: 'abstract',
    w: 30, h: 20,
    palette: { A: '#000033', B: '#000044', C: '#000066', D: '#000088', E: '#0000AA', F: '#0000CC', G: '#0000EE', H: '#0022FF', I: '#0044FF', J: '#0066FF' },
    rows: [
      'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
      'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
      'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
      'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
      'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
      'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
      'DDDDDDDDDDDDDDDDDDDDDDDDDDDD',
      'DDDDDDDDDDDDDDDDDDDDDDDDDDDD',
      'EEEEEEEEEEEEEEEEEEEEEEEEEEEEEE',
      'EEEEEEEEEEEEEEEEEEEEEEEEEEEEEE',
      'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
      'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
      'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
      'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
      'HHHHHHHHHHHHHHHHHHHHHHHHHHHHHH',
      'HHHHHHHHHHHHHHHHHHHHHHHHHHHHHH',
      'IIIIIIIIIIIIIIIIIIIIIIIIIIIIII',
      'IIIIIIIIIIIIIIIIIIIIIIIIIIIIII',
      'JJJJJJJJJJJJJJJJJJJJJJJJJJJJ',
      'JJJJJJJJJJJJJJJJJJJJJJJJJJJJ',
    ],
  },
  checkerboard: {
    cat: 'abstract',
    w: 30, h: 20,
    palette: { w: '#EEEEEE', b: '#333333' },
    rows: [
      'wwwbbbwwwbbbwwwbbbwwwbbbwwwbbb',
      'wwwbbbwwwbbbwwwbbbwwwbbbwwwbbb',
      'wwwbbbwwwbbbwwwbbbwwwbbbwwwbbb',
      'bbbwwwbbbwwwbbbwwwbbbwwwbbbwww',
      'bbbwwwbbbwwwbbbwwwbbbwwwbbbwww',
      'bbbwwwbbbwwwbbbwwwbbbwwwbbbwww',
      'wwwbbbwwwbbbwwwbbbwwwbbbwwwbbb',
      'wwwbbbwwwbbbwwwbbbwwwbbbwwwbbb',
      'wwwbbbwwwbbbwwwbbbwwwbbbwwwbbb',
      'bbbwwwbbbwwwbbbwwwbbbwwwbbbwww',
      'bbbwwwbbbwwwbbbwwwbbbwwwbbbwww',
      'bbbwwwbbbwwwbbbwwwbbbwwwbbbwww',
      'wwwbbbwwwbbbwwwbbbwwwbbbwwwbbb',
      'wwwbbbwwwbbbwwwbbbwwwbbbwwwbbb',
      'wwwbbbwwwbbbwwwbbbwwwbbbwwwbbb',
      'bbbwwwbbbwwwbbbwwwbbbwwwbbbwww',
      'bbbwwwbbbwwwbbbwwwbbbwwwbbbwww',
      'bbbwwwbbbwwwbbbwwwbbbwwwbbbwww',
      'wwwbbbwwwbbbwwwbbbwwwbbbwwwbbb',
      'wwwbbbwwwbbbwwwbbbwwwbbbwwwbbb',
    ],
  },
};

export function getBgCategories() {
  return BG_CATEGORIES;
}

export function getBgNames() {
  return Object.keys(DEFS);
}

export function getBgDef(name) {
  return DEFS[name] || null;
}

export function renderBg(name, scale = 1) {
  const def = DEFS[name];
  if (!def) return null;
  const canvas = document.createElement('canvas');
  canvas.width = def.w * scale;
  canvas.height = def.h * scale;
  const ctx = canvas.getContext('2d');
  for (let r = 0; r < def.rows.length; r++) {
    const row = def.rows[r];
    for (let c = 0; c < row.length; c++) {
      const ch = row[c];
      const color = def.palette[ch];
      if (!color) continue;
      ctx.fillStyle = color;
      ctx.fillRect(c * scale, r * scale, scale, scale);
    }
  }
  return canvas;
}

export function renderBgThumb(name) {
  return renderBg(name, 3);
}
