export const ISSUE_CODES = {
  EMPTY_SOURCE: "EMPTY_SOURCE",
  CPP_UNSUPPORTED_CONSTRUCT: "CPP_UNSUPPORTED_CONSTRUCT",
  UNSUPPORTED_SYNTAX: "UNSUPPORTED_SYNTAX",
  NO_EXECUTABLE_NODES: "NO_EXECUTABLE_NODES",
  INTERPRETER_DIAGNOSTIC: "INTERPRETER_DIAGNOSTIC",

  VALIDATION_ERROR: "VALIDATION_ERROR",
  KIT_CAPABILITY_MISMATCH: "KIT_CAPABILITY_MISMATCH",
  KIT_RUNTIME_MAPPING_MISSING: "KIT_RUNTIME_MAPPING_MISSING",
  NUMERIC_RANGE_INVALID: "NUMERIC_RANGE_INVALID",
  NUMERIC_INVALID: "NUMERIC_INVALID",
  KIT_ACTION_UNREGISTERED: "KIT_ACTION_UNREGISTERED",
  ACTION_REQUIRED: "ACTION_REQUIRED",

  COLLISION_DETECTED: "COLLISION_DETECTED",
  CALL_UNRESOLVED: "CALL_UNRESOLVED",
  CALL_STACK_OVERFLOW: "CALL_STACK_OVERFLOW",
  KIT_ACTION_UNSUPPORTED: "KIT_ACTION_UNSUPPORTED",
  KIT_ACTION_NO_KINEMATICS: "KIT_ACTION_NO_KINEMATICS",
  RETURN_OUTSIDE_FUNCTION: "RETURN_OUTSIDE_FUNCTION",
  LOOP_SAFETY_CAP: "LOOP_SAFETY_CAP",
  RUNTIME_DIAGNOSTIC: "RUNTIME_DIAGNOSTIC",
} as const;

export type IssueCode = (typeof ISSUE_CODES)[keyof typeof ISSUE_CODES];
export type IssueSeverity = "error" | "warning" | "info";
export type IssueCategory = "syntax" | "semantic" | "runtime";

