import type { EditablePropertyDescriptor, SimulatorObjectDefinition } from "./types";

const COLOR_PROP: EditablePropertyDescriptor = {
  id: "color",
  label: "Color",
  control: "color",
  description: "Primary render color",
};

const STATIC_FRICTION_PROP: EditablePropertyDescriptor = {
  id: "friction",
  label: "Friction",
  control: "number",
  min: 0,
  max: 3,
  step: 0.1,
  description: "Surface friction multiplier",
};

const COMMON_DYNAMIC_PROPS: EditablePropertyDescriptor[] = [
  {
    id: "mass_kg",
    label: "Mass",
    control: "number",
    min: 0.1,
    max: 20,
    step: 0.1,
    unit: "kg",
  },
  {
    id: "restitution",
    label: "Bounciness",
    control: "number",
    min: 0,
    max: 1,
    step: 0.05,
  },
  STATIC_FRICTION_PROP,
];

export const SIMULATOR_OBJECT_LIBRARY: SimulatorObjectDefinition[] = [
  {
    id: "nav_wall_basic",
    displayName: "Wall",
    description: "Static barrier for lanes and boundaries.",
    categoryId: "navigation_mapping",
    icon: "Square",
    difficulty: "beginner",
    tags: ["wall", "boundary", "barrier"],
    aliases: ["perimeter", "border"],
    placement: { objectType: "wall", shape: "box", sizeCm: { x: 120, y: 28, z: 18 }, color: "#6b7280", physicsBody: "static" },
    editableProperties: [COLOR_PROP, STATIC_FRICTION_PROP],
    physicsBehavior: { bodyType: "static", movable: false, friction: 1.1, notes: "Primary collision barrier" },
    contactBehavior: {
      contactMode: "solid",
      surfaceType: "default",
      frictionCoefficient: 1.1,
    },
    sensorInteraction: [{ sensorKind: "distance", behavior: "Returns nearest wall distance" }],
    eventsEmitted: [],
  },
  {
    id: "nav_maze_wall",
    displayName: "Maze Wall",
    description: "Thin strip wall segment for maze corridors.",
    categoryId: "navigation_mapping",
    icon: "Columns",
    difficulty: "beginner",
    tags: ["maze", "wall", "navigation"],
    placement: { objectType: "wall", shape: "box", sizeCm: { x: 90, y: 26, z: 6 }, color: "#64748b", physicsBody: "static" },
    editableProperties: [COLOR_PROP],
    physicsBehavior: { bodyType: "static", movable: false, friction: 1.15 },
    contactBehavior: {
      contactMode: "solid",
      surfaceType: "default",
      frictionCoefficient: 1.15,
    },
    sensorInteraction: [{ sensorKind: "distance", behavior: "Distance obstacle in maze path" }],
    eventsEmitted: [],
  },
  {
    id: "nav_moving_obstacle",
    displayName: "Moving Obstacle",
    description: "Obstacle intended for scripted path motion.",
    categoryId: "navigation_mapping",
    icon: "MoveHorizontal",
    difficulty: "advanced",
    tags: ["moving", "obstacle", "navigation"],
    placement: { objectType: "obstacle", shape: "box", sizeCm: { x: 34, y: 18, z: 34 }, color: "#ef4444", physicsBody: "kinematic", renderShape: "box" },
    editableProperties: [COLOR_PROP, { id: "speed_cm_s", label: "Path Speed", control: "number", min: 1, max: 120, step: 1 }],
    physicsBehavior: { bodyType: "kinematic", movable: true, friction: 1.0, notes: "Can be moved by mission scripts" },
    sensorInteraction: [{ sensorKind: "distance", behavior: "Dynamic obstacle detection" }],
    eventsEmitted: [{ event: "obstacle.path.loop", description: "Triggered when obstacle completes path cycle" }],
  },
  {
    id: "nav_ramp",
    displayName: "Ramp",
    description: "Inclined platform marker for navigation challenges.",
    categoryId: "navigation_mapping",
    icon: "Mountain",
    difficulty: "advanced",
    tags: ["ramp", "incline", "terrain"],
    placement: { objectType: "obstacle", shape: "box", sizeCm: { x: 52, y: 18, z: 42 }, color: "#9ca3af", physicsBody: "static", renderShape: "ramp" },
    editableProperties: [COLOR_PROP, { id: "slope_deg", label: "Slope", control: "number", min: 5, max: 45, step: 1 }],
    physicsBehavior: { bodyType: "static", movable: false, friction: 0.9 },
    contactBehavior: {
      contactMode: "solid",
      surfaceType: "ramp",
      frictionCoefficient: 0.9,
      slopeDeg: 14,
      rampEntrySide: "positive_x",
      rampSideBlocking: true,
      rampDescentAssist: 0.15,
    },
    sensorInteraction: [{ sensorKind: "gyro", behavior: "Can induce heading tilt/roll in advanced physics modes" }],
    eventsEmitted: [],
  },
  {
    id: "nav_waypoint_marker",
    displayName: "Waypoint Marker",
    description: "Marker used as waypoint checkpoints.",
    categoryId: "navigation_mapping",
    icon: "MapPin",
    difficulty: "beginner",
    tags: ["waypoint", "marker", "path"],
    placement: { objectType: "target_zone", shape: "flat_zone", sizeCm: { x: 24, y: 6, z: 24 }, color: "#38bdf8", physicsBody: "static", renderShape: "waypoint_marker" },
    editableProperties: [COLOR_PROP, { id: "waypoint_id", label: "Waypoint ID", control: "text" }],
    physicsBehavior: { bodyType: "static", movable: false },
    sensorInteraction: [{ sensorKind: "color", behavior: "Visible marker color for floor sensor routes" }],
    eventsEmitted: [{ event: "waypoint.enter", description: "Robot entered waypoint area" }],
  },

  {
    id: "sensor_line_track",
    displayName: "Line Track",
    description: "Line-following segment for optical sensors.",
    categoryId: "sensor_detection",
    icon: "Minus",
    difficulty: "beginner",
    tags: ["line", "track", "line follower"],
    placement: { objectType: "line_segment", shape: "flat_zone", sizeCm: { x: 20, y: 1, z: 20 }, color: "#111827", physicsBody: "static", renderShape: "flat_rect" },
    editableProperties: [COLOR_PROP],
    physicsBehavior: { bodyType: "static", movable: false },
    sensorInteraction: [{ sensorKind: "line", behavior: "Triggers line sensor detection" }],
    eventsEmitted: [{ event: "line.detected", description: "Robot line sensor crossed segment" }],
  },
  {
    id: "sensor_reflective_zone",
    displayName: "Reflective Zone",
    description: "High-reflectance patch for optical sensing exercises.",
    categoryId: "sensor_detection",
    icon: "Sun",
    difficulty: "advanced",
    tags: ["reflective", "light", "optical"],
    placement: { objectType: "color_zone", shape: "flat_zone", sizeCm: { x: 44, y: 6, z: 44 }, color: "#f8fafc", physicsBody: "static", renderShape: "flat_rect" },
    editableProperties: [COLOR_PROP],
    physicsBehavior: { bodyType: "static", movable: false },
    sensorInteraction: [{ sensorKind: "color", behavior: "Reports bright/reflective color value" }],
    eventsEmitted: [],
  },
  {
    id: "sensor_dark_zone",
    displayName: "Dark Zone",
    description: "Low-light patch for line and color discrimination.",
    categoryId: "sensor_detection",
    icon: "Moon",
    difficulty: "beginner",
    tags: ["dark", "low light", "line"],
    placement: { objectType: "color_zone", shape: "flat_zone", sizeCm: { x: 46, y: 6, z: 46 }, color: "#0f172a", physicsBody: "static", renderShape: "flat_rect" },
    editableProperties: [COLOR_PROP],
    physicsBehavior: { bodyType: "static", movable: false },
    sensorInteraction: [{ sensorKind: "color", behavior: "Reports dark color zone" }],
    eventsEmitted: [],
  },
  {
    id: "sensor_colored_beacon",
    displayName: "Colored Beacon",
    description: "Vertical marker for color/vision style targeting.",
    categoryId: "sensor_detection",
    icon: "Lamp",
    difficulty: "advanced",
    tags: ["beacon", "color target", "marker"],
    placement: { objectType: "obstacle", shape: "cylinder", sizeCm: { x: 18, y: 28, z: 18 }, color: "#fb7185", physicsBody: "static", renderShape: "cylinder" },
    editableProperties: [COLOR_PROP],
    physicsBehavior: { bodyType: "static", movable: false },
    sensorInteraction: [{ sensorKind: "distance", behavior: "Detectable vertical target for distance sensor" }],
    eventsEmitted: [{ event: "beacon.scanned", description: "Beacon was scanned by robot mission logic" }],
  },
  {
    id: "sensor_marker_tag",
    displayName: "Marker Tag",
    description: "Fiducial-style marker placeholder (AprilTag/QR-like).",
    categoryId: "sensor_detection",
    icon: "QrCode",
    difficulty: "advanced",
    tags: ["tag", "apriltag", "qr", "marker"],
    aliases: ["vision tag"],
    placement: { objectType: "target_zone", shape: "flat_zone", sizeCm: { x: 20, y: 4, z: 20 }, color: "#e5e7eb", physicsBody: "static", renderShape: "flat_rect" },
    editableProperties: [{ id: "tag_id", label: "Tag ID", control: "text" }],
    physicsBehavior: { bodyType: "static", movable: false },
    sensorInteraction: [{ sensorKind: "camera", behavior: "Reserved for future visual tag APIs" }],
    eventsEmitted: [{ event: "tag.detected", description: "Marker detected by vision module" }],
  },

  {
    id: "physics_pushable_block",
    displayName: "Pushable Block",
    description: "Dynamic cube for pushing/manipulation tasks.",
    categoryId: "interactive_physics",
    icon: "Box",
    difficulty: "beginner",
    tags: ["pushable", "block", "dynamic"],
    placement: { objectType: "obstacle", shape: "box", sizeCm: { x: 34, y: 22, z: 34 }, color: "#ef4444", physicsBody: "dynamic", renderShape: "box" },
    editableProperties: [COLOR_PROP, ...COMMON_DYNAMIC_PROPS],
    physicsBehavior: { bodyType: "dynamic", movable: true, friction: 1.1, massKg: 1.6 },
    contactBehavior: {
      contactMode: "solid",
      surfaceType: "default",
      frictionCoefficient: 1.1,
      pushResistance: 1.25,
    },
    sensorInteraction: [{ sensorKind: "distance", behavior: "Detected as movable obstacle" }],
    eventsEmitted: [{ event: "object.moved", description: "Block moved by contact" }],
  },
  {
    id: "physics_stackable_block",
    displayName: "Stackable Block",
    description: "Compact block intended for stacking missions.",
    categoryId: "interactive_physics",
    icon: "PackagePlus",
    difficulty: "advanced",
    tags: ["stack", "block", "manipulation"],
    placement: { objectType: "obstacle", shape: "box", sizeCm: { x: 22, y: 22, z: 22 }, color: "#f97316", physicsBody: "dynamic", renderShape: "box" },
    editableProperties: [COLOR_PROP, ...COMMON_DYNAMIC_PROPS],
    physicsBehavior: { bodyType: "dynamic", movable: true, friction: 1.2, massKg: 0.9 },
    sensorInteraction: [{ sensorKind: "distance", behavior: "Detectable stacking piece" }],
    eventsEmitted: [{ event: "stack.contact", description: "Block contacted stack surface" }],
  },
  {
    id: "physics_rolling_ball",
    displayName: "Rolling Ball",
    description: "Ball object for dribbling and trajectory exercises.",
    categoryId: "interactive_physics",
    icon: "Circle",
    difficulty: "beginner",
    tags: ["ball", "rolling", "soccer", "robocup"],
    aliases: ["vex ball", "game ball"],
    placement: { objectType: "obstacle", shape: "sphere", sizeCm: { x: 18, y: 18, z: 18 }, color: "#f59e0b", physicsBody: "dynamic", renderShape: "sphere" },
    editableProperties: [COLOR_PROP, ...COMMON_DYNAMIC_PROPS],
    physicsBehavior: { bodyType: "dynamic", movable: true, restitution: 0.3, friction: 0.7, massKg: 0.5 },
    contactBehavior: {
      contactMode: "solid",
      surfaceType: "default",
      frictionCoefficient: 0.7,
      restitutionCoefficient: 0.3,
      pushResistance: 0.75,
    },
    sensorInteraction: [{ sensorKind: "distance", behavior: "Tracked as dynamic spherical obstacle" }],
    eventsEmitted: [{ event: "ball.rolled", description: "Ball changed position" }],
  },
  {
    id: "physics_pickup_object",
    displayName: "Pickup Object",
    description: "Lightweight object for pickup/drop logic challenges.",
    categoryId: "interactive_physics",
    icon: "Hand",
    difficulty: "advanced",
    tags: ["pickup", "manipulation", "gripper"],
    placement: { objectType: "obstacle", shape: "box", sizeCm: { x: 16, y: 16, z: 16 }, color: "#22d3ee", physicsBody: "dynamic", renderShape: "box" },
    editableProperties: [COLOR_PROP, { id: "pickup_class", label: "Pickup Class", control: "text" }],
    physicsBehavior: { bodyType: "dynamic", movable: true, massKg: 0.25, friction: 0.8 },
    sensorInteraction: [{ sensorKind: "distance", behavior: "Short-range pickup detection target" }],
    eventsEmitted: [{ event: "pickup.collected", description: "Object collected by robot action" }],
  },
  {
    id: "physics_drop_zone",
    displayName: "Drop Zone",
    description: "Target area where pickup objects can be delivered.",
    categoryId: "interactive_physics",
    icon: "Inbox",
    difficulty: "beginner",
    tags: ["drop", "delivery", "zone"],
    placement: { objectType: "target_zone", shape: "flat_zone", sizeCm: { x: 44, y: 8, z: 44 }, color: "#34d399", physicsBody: "static", renderShape: "flat_rect" },
    editableProperties: [COLOR_PROP, { id: "accepts_class", label: "Accepts Class", control: "text" }],
    physicsBehavior: { bodyType: "static", movable: false },
    sensorInteraction: [{ sensorKind: "color", behavior: "Zone can be identified by floor color sensor" }],
    eventsEmitted: [{ event: "dropzone.scored", description: "Required object dropped in zone" }],
  },

  {
    id: "mission_scoring_bin",
    displayName: "Scoring Bin",
    description: "Primary scoring receptacle for object drop challenges.",
    categoryId: "mission_scoring",
    icon: "Archive",
    difficulty: "beginner",
    tags: ["scoring", "bin", "goal"],
    placement: { objectType: "target_zone", shape: "box", sizeCm: { x: 38, y: 18, z: 38 }, color: "#10b981", physicsBody: "static", renderShape: "box" },
    editableProperties: [COLOR_PROP, { id: "points", label: "Points", control: "number", min: 1, max: 100, step: 1 }],
    physicsBehavior: { bodyType: "static", movable: false },
    sensorInteraction: [{ sensorKind: "distance", behavior: "Target for close approach scoring tasks" }],
    eventsEmitted: [{ event: "score.bin", description: "Score awarded in bin" }],
  },
  {
    id: "mission_checkpoint",
    displayName: "Checkpoint",
    description: "Checkpoint trigger marker for path missions.",
    categoryId: "mission_scoring",
    icon: "FlagTriangleRight",
    difficulty: "beginner",
    tags: ["checkpoint", "path", "mission"],
    placement: { objectType: "target_zone", shape: "flat_zone", sizeCm: { x: 30, y: 6, z: 30 }, color: "#fbbf24", physicsBody: "static", renderShape: "waypoint_marker" },
    editableProperties: [{ id: "checkpoint_id", label: "Checkpoint ID", control: "text" }, COLOR_PROP],
    physicsBehavior: { bodyType: "static", movable: false },
    sensorInteraction: [{ sensorKind: "color", behavior: "Checkpoint floor signature" }],
    eventsEmitted: [{ event: "checkpoint.reached", description: "Robot reached checkpoint" }],
  },
  {
    id: "mission_pressure_plate",
    displayName: "Pressure Plate",
    description: "Plate that emits event when contacted.",
    categoryId: "mission_scoring",
    icon: "Square",
    difficulty: "advanced",
    tags: ["pressure", "plate", "trigger"],
    placement: { objectType: "target_zone", shape: "flat_zone", sizeCm: { x: 24, y: 5, z: 24 }, color: "#f97316", physicsBody: "static", renderShape: "flat_rect" },
    editableProperties: [COLOR_PROP, { id: "hold_ms", label: "Hold Time", control: "number", min: 0, max: 10000, step: 100, unit: "ms" }],
    physicsBehavior: { bodyType: "static", movable: false },
    sensorInteraction: [{ sensorKind: "touch", behavior: "Mission script can map wheel contact to plate activation" }],
    eventsEmitted: [{ event: "plate.activated", description: "Plate activation condition reached" }],
  },

  {
    id: "env_low_friction_zone",
    displayName: "Low-Friction Zone",
    description: "Slippery region reducing traction.",
    categoryId: "environment_effects",
    icon: "Droplets",
    difficulty: "advanced",
    tags: ["low friction", "slippery", "terrain"],
    placement: { objectType: "color_zone", shape: "flat_zone", sizeCm: { x: 60, y: 6, z: 60 }, color: "#93c5fd", physicsBody: "static", renderShape: "flat_rect" },
    editableProperties: [COLOR_PROP, { id: "friction_scale", label: "Friction Scale", control: "number", min: 0.1, max: 1, step: 0.05 }],
    physicsBehavior: { bodyType: "static", movable: false, friction: 0.3 },
    contactBehavior: {
      contactMode: "pass_through",
      surfaceType: "low_friction",
      frictionCoefficient: 0.3,
    },
    sensorInteraction: [{ sensorKind: "color", behavior: "Distinct floor color to anticipate slip zone" }],
    eventsEmitted: [{ event: "terrain.enter.low_friction", description: "Robot entered slippery zone" }],
  },
  {
    id: "env_high_friction_zone",
    displayName: "High-Friction Zone",
    description: "Sticky terrain reducing glide and drift.",
    categoryId: "environment_effects",
    icon: "Grip",
    difficulty: "advanced",
    tags: ["high friction", "sticky", "terrain"],
    placement: { objectType: "color_zone", shape: "flat_zone", sizeCm: { x: 60, y: 6, z: 60 }, color: "#60a5fa", physicsBody: "static", renderShape: "flat_rect" },
    editableProperties: [COLOR_PROP, { id: "friction_scale", label: "Friction Scale", control: "number", min: 1, max: 3, step: 0.1 }],
    physicsBehavior: { bodyType: "static", movable: false, friction: 1.8 },
    contactBehavior: {
      contactMode: "pass_through",
      surfaceType: "high_friction",
      frictionCoefficient: 1.8,
    },
    sensorInteraction: [{ sensorKind: "color", behavior: "Distinct floor color to identify grip zone" }],
    eventsEmitted: [{ event: "terrain.enter.high_friction", description: "Robot entered high-grip zone" }],
  },
  {
    id: "env_conveyor_belt",
    displayName: "Conveyor Belt",
    description: "Directional mover for object flow challenges.",
    categoryId: "environment_effects",
    icon: "ArrowRightLeft",
    difficulty: "advanced",
    tags: ["conveyor", "belt", "movement"],
    placement: { objectType: "obstacle", shape: "flat_zone", sizeCm: { x: 70, y: 8, z: 24 }, color: "#475569", physicsBody: "kinematic", renderShape: "flat_rect" },
    editableProperties: [{ id: "belt_speed_cm_s", label: "Belt Speed", control: "number", min: 1, max: 120, step: 1 }, COLOR_PROP],
    physicsBehavior: { bodyType: "kinematic", movable: true, friction: 0.9 },
    sensorInteraction: [{ sensorKind: "distance", behavior: "Obstacle present with directional motion metadata" }],
    eventsEmitted: [{ event: "belt.transfer", description: "Object transferred by conveyor zone" }],
  },

  {
    id: "agent_patrol_bot",
    displayName: "Patrol Bot",
    description: "Autonomous bot placeholder for dynamic missions.",
    categoryId: "multi_agent_dynamic",
    icon: "Bot",
    difficulty: "advanced",
    tags: ["patrol", "robot", "dynamic agent"],
    placement: { objectType: "obstacle", shape: "box", sizeCm: { x: 28, y: 16, z: 28 }, color: "#a78bfa", physicsBody: "kinematic", renderShape: "box" },
    editableProperties: [{ id: "patrol_profile", label: "Patrol Profile", control: "select", options: [{ value: "loop", label: "Loop" }, { value: "pingpong", label: "Ping Pong" }] }],
    physicsBehavior: { bodyType: "kinematic", movable: true, notes: "Controlled by mission runtime" },
    sensorInteraction: [{ sensorKind: "distance", behavior: "Treat as moving obstacle entity" }],
    eventsEmitted: [{ event: "agent.spotted", description: "Patrol bot spotted by robot logic" }],
  },
  {
    id: "agent_follow_bot",
    displayName: "Follow Bot",
    description: "Support robot that follows mission anchor rules.",
    categoryId: "multi_agent_dynamic",
    icon: "BotMessageSquare",
    difficulty: "advanced",
    tags: ["follow", "agent", "robot"],
    placement: { objectType: "obstacle", shape: "box", sizeCm: { x: 26, y: 16, z: 26 }, color: "#8b5cf6", physicsBody: "kinematic", renderShape: "box" },
    editableProperties: [{ id: "follow_distance_cm", label: "Follow Distance", control: "number", min: 10, max: 200, step: 5 }],
    physicsBehavior: { bodyType: "kinematic", movable: true },
    sensorInteraction: [{ sensorKind: "distance", behavior: "Dynamic obstacle with follow behavior" }],
    eventsEmitted: [{ event: "agent.following", description: "Follow behavior active" }],
  },

  {
    id: "logic_trigger_zone",
    displayName: "Trigger Zone",
    description: "Event zone that emits custom trigger events.",
    categoryId: "logic_event",
    icon: "Zap",
    difficulty: "advanced",
    tags: ["trigger", "event", "zone", "logic"],
    placement: { objectType: "target_zone", shape: "flat_zone", sizeCm: { x: 34, y: 6, z: 34 }, color: "#f43f5e", physicsBody: "static", renderShape: "flat_rect" },
    editableProperties: [{ id: "trigger_id", label: "Trigger ID", control: "text" }, COLOR_PROP],
    physicsBehavior: { bodyType: "static", movable: false },
    sensorInteraction: [{ sensorKind: "color", behavior: "Optional visual cue for trigger location" }],
    eventsEmitted: [{ event: "trigger.fired", description: "Trigger zone fired event payload" }],
  },
  {
    id: "logic_signal_emitter",
    displayName: "Signal Emitter",
    description: "Emitter object that can broadcast logic signals.",
    categoryId: "logic_event",
    icon: "RadioTower",
    difficulty: "advanced",
    tags: ["signal", "emitter", "event"],
    placement: { objectType: "obstacle", shape: "cylinder", sizeCm: { x: 16, y: 26, z: 16 }, color: "#fb7185", physicsBody: "static", renderShape: "cylinder" },
    editableProperties: [{ id: "signal_channel", label: "Channel", control: "text" }],
    physicsBehavior: { bodyType: "static", movable: false },
    sensorInteraction: [{ sensorKind: "distance", behavior: "Can be targeted as logic source object" }],
    eventsEmitted: [{ event: "signal.emit", description: "Emitter sent logic signal" }],
  },

  {
    id: "comp_field_tile",
    displayName: "Field Tile",
    description: "Competition tile for field layout and path marking.",
    categoryId: "competition_field",
    icon: "Grid2x2",
    difficulty: "beginner",
    tags: ["field", "tile", "competition"],
    placement: { objectType: "color_zone", shape: "flat_zone", sizeCm: { x: 60, y: 5, z: 60 }, color: "#334155", physicsBody: "static", renderShape: "flat_rect" },
    editableProperties: [COLOR_PROP],
    physicsBehavior: { bodyType: "static", movable: false },
    sensorInteraction: [{ sensorKind: "color", behavior: "Field tile color reading" }],
    eventsEmitted: [],
  },
  {
    id: "comp_ring",
    displayName: "Ring",
    description: "Ring game element for scoring and manipulation.",
    categoryId: "competition_field",
    icon: "CircleDot",
    difficulty: "beginner",
    tags: ["ring", "game piece", "competition"],
    placement: { objectType: "obstacle", shape: "cylinder", sizeCm: { x: 14, y: 10, z: 14 }, color: "#f97316", physicsBody: "dynamic", renderShape: "ring" },
    editableProperties: [COLOR_PROP, ...COMMON_DYNAMIC_PROPS],
    physicsBehavior: { bodyType: "dynamic", movable: true, massKg: 0.2, friction: 0.6 },
    sensorInteraction: [{ sensorKind: "distance", behavior: "Small movable object target" }],
    eventsEmitted: [{ event: "ring.scored", description: "Ring reached scoring structure" }],
  },
  {
    id: "comp_disc",
    displayName: "Disc",
    description: "Flat disc element for launch and collection challenges.",
    categoryId: "competition_field",
    icon: "Disc",
    difficulty: "advanced",
    tags: ["disc", "launch", "competition"],
    placement: { objectType: "obstacle", shape: "cylinder", sizeCm: { x: 16, y: 4, z: 16 }, color: "#0ea5e9", physicsBody: "dynamic", renderShape: "disc" },
    editableProperties: [COLOR_PROP, ...COMMON_DYNAMIC_PROPS],
    physicsBehavior: { bodyType: "dynamic", movable: true, massKg: 0.12, friction: 0.45, restitution: 0.2 },
    sensorInteraction: [{ sensorKind: "distance", behavior: "Thin object detection challenge" }],
    eventsEmitted: [{ event: "disc.hit_target", description: "Disc collided with mission target" }],
  },
  {
    id: "comp_cube",
    displayName: "Cube",
    description: "Cube element used in stacking and sorting tasks.",
    categoryId: "competition_field",
    icon: "Box",
    difficulty: "beginner",
    tags: ["cube", "sorting", "stacking", "competition"],
    placement: { objectType: "obstacle", shape: "box", sizeCm: { x: 18, y: 18, z: 18 }, color: "#22c55e", physicsBody: "dynamic", renderShape: "box" },
    editableProperties: [COLOR_PROP, ...COMMON_DYNAMIC_PROPS],
    physicsBehavior: { bodyType: "dynamic", movable: true, massKg: 0.45, friction: 1.0 },
    sensorInteraction: [{ sensorKind: "distance", behavior: "Standard game piece obstacle" }],
    eventsEmitted: [{ event: "cube.placed", description: "Cube placed in mission zone" }],
  },
];

export const SIMULATOR_OBJECT_BY_ID = new Map(SIMULATOR_OBJECT_LIBRARY.map((entry) => [entry.id, entry]));

